# Generated by Django 2.1.7 on 2019-03-04 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(default='user', max_length=50)),
                ('sender_Id', models.CharField(default='ROBERMS', max_length=11)),
                ('access_code', models.CharField(default='710083', max_length=11)),
                ('service_id', models.CharField(default='6015752000133434', max_length=50)),
                ('business_name', models.CharField(default='Buiness Name', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
