# Generated by Django 2.1.7 on 2019-03-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_outgoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
