# Generated by Django 2.1.7 on 2019-03-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20190306_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing',
            name='text_message',
            field=models.TextField(max_length=600),
        ),
    ]
