# Generated by Django 2.1.7 on 2019-03-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_auto_20190306_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('user', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Ingredience Categories',
            },
        ),
    ]
