# Generated by Django 2.1.7 on 2019-03-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_upload_csv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='name',
            new_name='author',
        ),
    ]
